src/accounts/urls.py
from django.urls import path
from django.contrib.auth import login

from . views import register


app_name = 'accounts'

urlpatterns = [
    path('register/' , register , name='register')

]

src/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('' , views.home , name='home') , 

]

src/olx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('', include('home.urls' , namespace='home')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('products/', include('product.urls', namespace='products')),
    path('accounts/', include('accounts.urls' , namespace='accounts')),
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/product/urls.py
from django.urls import path
from . import views

app_name = 'product'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<str:category_slug>', views.product_list, name='product_list_category'),
    path('detail/<str:product_slug>', views.product_detail, name='product_detail')
]

src/home/models.py
from django.db import models

# Create your models here.

src/product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify

class Products(models.Model):

    CONDITION_TYPE = (
        ("New","New"),
        ("Used for less than a Month","Used for less than a Month"),
        ("Used for less than  3 Months","Used for less than 3 Months"),
        ("Used for less than  6 Months","Used for less than 6 Months"),
        ("Used for more than  6 Months","Used for more than 6 Months")
        
    )
    
    name        = models.CharField(max_length=100)
    owner       = models.ForeignKey(User, on_delete=models.CASCADE)
    category    = models.ForeignKey('Category',on_delete=models.SET_NULL, null=True)
    brand       = models.ForeignKey('Brand',on_delete=models.SET_NULL, null=True)
    description = models.TextField(max_length=500)
    condition   = models.CharField(max_length=100, choices=CONDITION_TYPE)
    price       = models.DecimalField(max_digits=11,decimal_places=2)
    image       = models.ImageField(upload_to='main_product/', blank=True, null=True)
    created     = models.DateTimeField(default=timezone.now)
    
    slug        = models.SlugField(null=True, blank=True)

    def save(self, *args, **kwargs):
        '''overrides save action'''
        
        if not self.slug and self.name:
            self.slug = slugify(self.name)

        super(Products, self).save(*args, **kwargs)    

    class Meta:
        verbose_name        = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    product = models.ForeignKey(Products,  on_delete=models.CASCADE)
    image   = models.ImageField(upload_to='product/', blank=True, null=True)

    class Meta:
        verbose_name        = 'Product_image'
        verbose_name_plural = 'Product_images'

    def __str__(self):
        return self.product.name

class Category(models.Model):
    
    category_name = models.CharField(max_length=50)
    image         = models.ImageField(upload_to='category/', blank=True,null=True)

    slug          = models.SlugField(null=True, blank=True)

    def save(self, *args, **kwargs):
        '''overrides save action'''
        
        if not self.slug and self.category_name:
            self.slug = slugify(self.category_name)

        super(Category, self).save(*args, **kwargs)     


    class Meta:
        verbose_name        = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.category_name
    

class Brand(models.Model):
    
    brand_name = models.CharField(max_length=50)
    

    class Meta:
        verbose_name        = 'brand'
        verbose_name_plural = 'brands'

    def __str__(self):
        return self.brand_name

src/accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    class Meta():
        model = User
        fields = ['first_name' , 'last_name' ,'username' , 'email' , 'password' ]

src/accounts/views.py
from django.shortcuts import render , redirect

from .forms import UserForm

# Create your views here.


def register(request):
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user_form.save()
            return redirect('/products')

    else:
        user_form = UserForm()

    context = {'user_form' : user_form}

    return render(request , 'registration/register.html' , context)

src/home/views.py
from django.shortcuts import render
from product.models import Products , Category
# Create your views here.

def home(request):
    
    all_category = Category.objects.all() 
    products = Products.objects.all()

    template = 'home.html'
    context = { 'all_category' : all_category , 'products' : products}

    return render(request , template , context)

src/product/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from django.db.models import Count, Q
from django.shortcuts import get_object_or_404

from .models import ProductImage, Products, Category


def product_list(request, category_slug=None):

    category         = None 
    product_list     = Products.objects.all()
    category_list    = Category.objects.annotate(total_products=Count('products'))
    
    if category_slug:
        category     = get_object_or_404(Category,slug=category_slug)
        product_list = product_list.filter(category =category)

    search_query     = request.GET.get('q')

    if search_query:
        product_list = product_list.filter(
            Q(name__icontains                           = search_query) |
            Q(condition__icontains                      = search_query) |
            Q(description__icontains                    = search_query) |
            Q(brand__brand_name__icontains              = search_query) |
            Q(category__category_name__icontains        = search_query)
        )


    paginator        = Paginator(product_list, 6)
    page             = request.GET.get('page')
    product_list     = paginator.get_page(page) 
    template         = 'Products/product_list.html'
    context          = {
                        'product_list'  : product_list,
                        'category_list' : category_list,
                        'category'      : category
        }

    return render(request ,template, context)

def product_detail(request,product_slug):

    product_detail = get_object_or_404(Products,slug=product_slug)

    Product_image  = ProductImage.objects.filter(product=product_detail)

    template       = 'Products/product_detail.html'

    context        = {
                        'product_detail' : product_detail,
                        'product_image'  : Product_image
    }

    return render(request, template, context)

src/product/templates/Products/product_detail.html
{% extends 'base.html' %}

{% load static %}

{% block body %}

	<!-- breadcrumbs -->
	<div class="w3layouts-breadcrumbs text-center">
		<div class="container">
			<span class="agile-breadcrumbs">
			<a href="/"><i class="fa fa-home home_1"></i></a> / 
			<a href="{% url 'products:product_list'%}">All Ads</a> / 
			<a href="#">{{ product_detail.category}}</a> / 
			<span>{{product_detail.name}}</span></span>
		</div>
	</div>
	<!-- //breadcrumbs -->

	<!--single-page-->
	<div class="single-page main-grid-border">
		<div class="container">
			<div class="product-desc">
				<div class="col-md-7 product-view">
					<h2>{{ product_detail.name}}</h2>
					<p> <i class="glyphicon glyphicon-map-marker"></i><a href="#">state</a>, <a href="#">city</a>| Added on {{product_detail.created}}, Ad ID: 987654321</p>
					<div class="flexslider">
						<ul class="slides">
							{% for image in  Product_image %}

							<li data-thumb="{{image.image.url }}">
								<img src="{{image.image.url }}" />
							</li>

						   {% endfor %}
						</ul>
					</div>
					<!-- FlexSlider -->
					<script defer src="{% static 'js/jquery.flexslider.js' %}"></script>

					<script>
					// Can also be used with $(document).ready()
					$(window).load(function() {
					  $('.flexslider').flexslider({
						animation: "slide",
						controlNav: "thumbnails"
					  });
					});
					</script>
					<!-- //FlexSlider -->
					<div class="product-details">
						<h4><span class="w3layouts-agileinfo">Brand </span> : <a href="#">{{product_detail.brand}}</a><div class="clearfix"></div></h4>
						<h4><span class="w3layouts-agileinfo">Views </span> : <strong>150</strong></h4>
						<h4><span class="w3layouts-agileinfo">Summary</span> :<p>{{product_detail.description}}</p><div class="clearfix"></div></h4>
					
					</div>
				</div>
				<div class="col-md-5 product-details-grid">
					<div class="item-price">
						<div class="product-price">
							<p class="p-price">Price</p>
							<h3 class="rate">Ksh {{product_detail.price}}</h3>
							<div class="clearfix"></div>
						</div>
						<div class="condition">
							<p class="p-price">Condition</p>
							<h4>{{ product_detail.condition }}</h4>
							<div class="clearfix"></div>
						</div>
						<div class="itemtype">
							<p class="p-price">Item Type</p>
							<h4>{{product_detail.category}}</h4>
							<div class="clearfix"></div>
						</div>
					</div>
					<div class="interested text-center">
						<h4>Interested in this Ad?<small> Contact the Seller!</small></h4>
						<p><i class="glyphicon glyphicon-earphone"></i>00-85-9875462655</p>
					</div>
						<div class="tips">
						<h4>Safety Tips for Buyers</h4>
							<ol>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
							</ol>
						</div>
				</div>
			<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--//single-page-->


{% endblock body %}

src/product/templates/Products/product_list.html
{% extends 'base.html' %}

{% block body %}

	<!-- breadcrumbs -->
	<div class="w3layouts-breadcrumbs text-center">
		<div class="container">
			<span class="agile-breadcrumbs"><a href="{% url 'products:product_list'%}"><i class="fa fa-home home_1"></i> /<span> All Ads</span></span></a>
			{% if category %}
				<span class="agile-breadcrumbs"><a href="#"></a>/<span>{{ category }}</span></span>
			{% endif %}
		</div>
	</div>
	<!-- //breadcrumbs -->



	<!-- Products -->
	<div class="total-ads main-grid-border">
		<div class="container">
			<div class="select-box">
				<div class="select-city-for-local-ads ads-list">
					<label>Select your city to see local ads</label>
						<select>
							<optgroup label="Popular Cities">
													<option selected style="display:none;color:#eee;">Select City</option>
													<option>Nairobi</option>
													<option>Mombasa</option>
													<option>Kisumu</option>
												
							</optgroup>
											
												<optgroup label="More Cities">
												
											
													<optgroup label="Nairobi">
														<option>Pangani</option>
														<option>Kilimani</option>
														<option>Kawangware</option>
														<option>Roysambu</option>
														<option>Umoja</option>         														
													</optgroup>
													<optgroup label="Mombasa">
														<option>Tudor</option>
														<option>Majengo</option>
														<option>Kisauni</option>
														<option>Bamburi</option>
														<option>Likoni</option>            														
													</optgroup>
													
														
												</optgroup>
			            </select>
				</div>
				<div class="browse-category ads-list">
					<label>Browse Categories</label>
					<select class="selectpicker show-tick" data-live-search="true">
					  <option data-tokens="Mobiles">All</option>
					  <option data-tokens="Mobiles">Mobiles</option>
					  <option data-tokens="Electronics & Appliances">Electronics & Appliances</option>
					  <option data-tokens="Cars">Cars</option>
					  <option data-tokens="Bikes">Bikes</option>
					  <option data-tokens="Furniture">Furniture</option>
					  <option data-tokens="Pets">Pets</option>
					  <option data-tokens="Books, Sports & Hobbies">Books, Sports & Hobbies</option>
					  <option data-tokens="Fashion">Fashion</option>
					  <option data-tokens="Kids">Kids</option>
					  <option data-tokens="Services">Services</option>
					  <option data-tokens="Jobs">Jobs</option>
					  <option data-tokens="Real Estate">Real Estate</option>
					</select>
				</div>
				<div class="search-product ads-list">
					<label>Search for a specific product</label>
					<div class="search">
						<div id="custom-search-input">
						<div class="input-group">
							<input type="text" class="form-control input-lg" placeholder="Iphone" />
							<span class="input-group-btn">
								<button class="btn btn-info btn-lg" type="button">
									<i class="glyphicon glyphicon-search"></i>
								</button>
							</span>
						</div>
					</div>
					</div>
				</div>
				<div class="clearfix"></div>
			</div>
			<div class="all-categories">
				<h3> Select your category and find the perfect ad</h3>
				<ul class="all-cat-list">
				{% for  category in category_list %}
					
			      <li><a href="{% url 'products:product_list_category' category.slug %}">{{category.category_name}} <span class="num-of-ads">({{category.total_products}})</span></a></li>
				
				{% endfor %}

				</ul>
			</div>
			<div class="ads-grid">
				<div class="side-bar col-md-3">
				

				<div class="search-hotel">
					<h3 class="agileits-sear-head">Name contains</h3>
					<form method='GET' action = "{% url 'product:product_list' %}">
						<input type="text"  name = "q" value="Product name..." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Product name...';}" required="">
						<input type="submit" value=" ">
					</form>
				</div>
				
				
				
				<div class="w3ls-featured-ads">
					<h2 class="sear-head fer">Featured Ads</h2>
					<div class="w3l-featured-ad">
						<a href="single.html">
							<div class="w3-featured-ad-left">
								<img src="images/f1.jpg" title="ad image" alt="" />
							</div>
							<div class="w3-featured-ad-right">
								<h4>Lorem Ipsum is simply dummy text of the printing industry</h4>
								<p>$ 450</p>
							</div>
							<div class="clearfix"></div>
						</a>
					</div>
				

					<div class="clearfix"></div>
				</div>

				</div>

				<div class="agileinfo-ads-display col-md-9">
					<div class="wrapper">					
					<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
					
					  <div id="myTabContent" class="tab-content">
						<div role="tabpanel" class="tab-pane fade in active" id="home" aria-labelledby="home-tab">
						   <div>
												<div id="container">
						
								
								<div class="clearfix"></div>
							<ul class="list">
							{% for product in product_list%}
								<a href="{% url 'products:product_detail' product.slug %}">
									<li>
									<img src="{{ product.image.url}}" title="" alt="" />
									<section class="list-left">
									<h5 class="title">{{ product.name }}</h5>
									<span class="adprice">Ksh {{ product.price}}</span>
									<p class="catpath">{{ product.category }} » {{ product.brand }}</p>
									</section>
									<section class="list-right">
									<span class="date">{{ product.created}}</span>
									<span class="cityname">City name</span>
									</section>
									<div class="clearfix"></div>
									</li> 
								</a>
						
							{% endfor %}	
							</ul>
						</div>
							</div>
						</div>
					
			            {% if  product_list.has_other_pages  %}

						<ul class="pagination pagination-sm">

						{% if  product_list.has_previous %}

						        <li><a href="?page={{ contactsproduct_list.previous_page_number }}">Prev</a></li>

						{% else %}

								<li class='disabled'></li>

						{% endif %}

						{% for pages in product_list.paginator.page_range %}
							
							{% if product_list.number == pages %}
							
									<li><a href="#">{{ pages }}</a></li>

							{% else %}

									<li><a href="?page={{pages}}">{{ pages }}</a></li>

							{% endif %}
							 
							

						{% endfor %}
							  

						{% if product_list.has_next %}
						    
							<li><a href="?page={{ product_list.next_page_number }}">Next</a></li>
					    		
						{% else %}

								<li class='disabled'></li>								
						
						{% endif %}	
							
						</ul>

						{% endif %}

					  </div>
					</div>
				</div>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>	
	</div>
	<!-- // Products -->




{% endblock body %}

src/templates/base.html
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>OlxClone  | All Classifieds </title>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"><!-- bootstrap-CSS -->
<link rel="stylesheet" href="{% static 'css/bootstrap-select.css' %}"><!-- bootstrap-select-CSS -->
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" /><!-- style.css -->
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui1.css' %}">
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" /><!-- fontawesome-CSS -->

<!-- meta tags -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Resale Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //meta tags -->
<!--fonts-->
<link href='//fonts.googleapis.com/css?family=Ubuntu+Condensed' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<!--//fonts-->	
<!-- js -->
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<!-- js -->
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/bootstrap-select.js' %}"></script>
<script>
  $(document).ready(function () {
    var mySelect = $('#first-disabled2');

    $('#special').on('click', function () {
      mySelect.find('option:selected').prop('disabled', true);
      mySelect.selectpicker('refresh');
    });

    $('#special2').on('click', function () {
      mySelect.find('option:disabled').prop('disabled', false);
      mySelect.selectpicker('refresh');
    });

    $('#basic2').selectpicker({
      liveSearch: true,
      maxOptions: 1
    });
  });
</script>


<!-- switcher-grid and list alignment -->
	
<script type="text/javascript">
$(document).ready(function () {    
var elem=$('#container ul');      
	$('#viewcontrols a').on('click',function(e) {
		if ($(this).hasClass('gridview')) {
			elem.fadeOut(1000, function () {
				$('#container ul').removeClass('list').addClass('grid');
				$('#viewcontrols').removeClass('view-controls-list').addClass('view-controls-grid');
				$('#viewcontrols .gridview').addClass('active');
				$('#viewcontrols .listview').removeClass('active');
				elem.fadeIn(1000);
			});						
		}
		else if($(this).hasClass('listview')) {
			elem.fadeOut(1000, function () {
				$('#container ul').removeClass('grid').addClass('list');
				$('#viewcontrols').removeClass('view-controls-grid').addClass('view-controls-list');
				$('#viewcontrols .gridview').removeClass('active');
				$('#viewcontrols .listview').addClass('active');
				elem.fadeIn(1000);
			});									
		}
	});
});
</script>
<!-- //switcher-grid and list alignment -->
</head>
<body>
	<!-- Navigation -->

	<!-- header -->
	<header>
		<div class="w3ls-header"><!--header-one--> 
			<div class="w3ls-header-left">
				<p><a href="mobileapp.html"><i class="fa fa-download" aria-hidden="true"></i>Download Mobile App </a></p>
			</div>
			<div class="w3ls-header-right">
				<ul>
					<li class="dropdown head-dpdn">
						<a href="signin.html" aria-expanded="false"><i class="fa fa-user" aria-hidden="true"></i> Sign In</a>
					</li>
					<li class="dropdown head-dpdn">
						<a href="help.html"><i class="fa fa-question-circle" aria-hidden="true"></i> Help</a>
					</li>
					

				</ul>
			</div>
			
			<div class="clearfix"> </div> 
		</div>
		<div class="container">
			<div class="agile-its-header">
				<div class="logo">
					<h1><a href="index.html"><span>Olx</span>Clone</a></h1>
				</div>
				<div class="agileits_search">
					<form action="#" method="post">
						<input name="Search" type="text" placeholder="How can we help you today?" required=" ">
						<select id="agileinfo_search" name="agileinfo_search" required="">
							<option value="">All Categories</option>
							<option value="Mobiles">Mobiles</option>
							<option value="Electronics & Appliances">Electronics & Appliances</option>
							<option value="Cars">Cars</option>
							<option value="Bikes">Bikes</option>
							<option value="Furnitures">Furnitures</option>
							<option value="Books, Sports & Hobbies">Books, Sports & Hobbies</option>
							<option value="Fashion">Fashion</option>
							<option value="Kids">Kids</option>
							<option value="Services">Services</option>
							<option value="Jobs">Jobs</option>
							<option value="Real Estates">Real Estates</option>
						</select>
						<button type="submit" class="btn btn-default" aria-label="Left Align">
							<i class="fa fa-search" aria-hidden="true"> </i>
						</button>
					</form>
				<a class="post-w3layouts-ad" href="post-ad.html">Post Free Ad</a>
				</div>	
				<div class="clearfix"></div>
			</div>
		</div>
	</header>

	<!-- //header -->
 {% block body %}

{% endblock body %}



		<!--footer section start-->		
		<footer>
			<div class="w3-agileits-footer-top">
				<div class="container">
					<div class="wthree-foo-grids">
						<div class="col-md-3 wthree-footer-grid">
							<h4 class="footer-head">Who We Are</h4>
							<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
							<p>The point of using Lorem Ipsum is that it has a more-or-less normal letters, as opposed to using 'Content here.</p>
						</div>
						<div class="col-md-3 wthree-footer-grid">
							<h4 class="footer-head">Help</h4>
							<ul>
								<li><a href="howitworks.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>How it Works</a></li>						
								<li><a href="sitemap.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Sitemap</a></li>
								<li><a href="faq.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Faq</a></li>
								<li><a href="feedback.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Feedback</a></li>
								<li><a href="contact.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Contact</a></li>
								<li><a href="typography.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Short codes</a></li>
								<li><a href="icons.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Icons Page</a></li>
							</ul>
						</div>
						<div class="col-md-3 wthree-footer-grid">
							<h4 class="footer-head">Information</h4>
							<ul>
								<li><a href="regions.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Locations Map</a></li>	
								<li><a href="terms.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Terms of Use</a></li>
								<li><a href="popular-search.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Popular searches</a></li>	
								<li><a href="privacy.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Privacy Policy</a></li>	
							</ul>
						</div>
						<div class="col-md-3 wthree-footer-grid">
							<h4 class="footer-head">Contact Us</h4>
							<span class="hq">Our headquarters</span>
							<address>
								<ul class="location">
									<li><span class="glyphicon glyphicon-map-marker"></span></li>
									<li>CENTER FOR FINANCIAL ASSISTANCE TO DEPOSED NIGERIAN ROYALTY</li>
								</ul>	
								<div class="clearfix"> </div>
								<ul class="location">
									<li><span class="glyphicon glyphicon-earphone"></span></li>
									<li>+0 561 111 235</li>
								</ul>	
								<div class="clearfix"> </div>
								<ul class="location">
									<li><span class="glyphicon glyphicon-envelope"></span></li>
									<li><a href="mailto:info@example.com">mail@example.com</a></li>
								</ul>						
							</address>
						</div>
						<div class="clearfix"></div>
					</div>						
				</div>	
			</div>	
			<div class="agileits-footer-bottom text-center">
			<div class="container">
				<div class="w3-footer-logo">
					<h1><a href="index.html"><span>Olx</span>Clone</a></h1>
				</div>
				<div class="w3-footer-social-icons">
					<ul>
						<li><a class="facebook" href="#"><i class="fa fa-facebook" aria-hidden="true"></i><span>Facebook</span></a></li>
						<li><a class="twitter" href="#"><i class="fa fa-twitter" aria-hidden="true"></i><span>Twitter</span></a></li>
						<li><a class="flickr" href="#"><i class="fa fa-flickr" aria-hidden="true"></i><span>Flickr</span></a></li>
						<li><a class="googleplus" href="#"><i class="fa fa-google-plus" aria-hidden="true"></i><span>Google+</span></a></li>
						<li><a class="dribbble" href="#"><i class="fa fa-dribbble" aria-hidden="true"></i><span>Dribbble</span></a></li>
					</ul>
				</div>
				<div class="copyrights">
					<p> © 2016 Resale. All Rights Reserved | Design by  <a href="http://w3layouts.com/"> W3layouts</a></p>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
		</footer>
        <!--footer section end-->
</body>
		<!-- Navigation-JavaScript -->
			<script src="{% static 'js/classie.js'%}"></script>
			<script src="{% static 'js/main.js'%}"></script>
		<!-- //Navigation-JavaScript -->
		<!-- here stars scrolling icon -->
			<script type="text/javascript">
				$(document).ready(function() {
					/*
						var defaults = {
						containerID: 'toTop', // fading element id
						containerHoverID: 'toTopHover', // fading element hover id
						scrollSpeed: 1200,
						easingType: 'linear' 
						};
					*/
										
					$().UItoTop({ easingType: 'easeOutQuart' });
										
					});
			</script>
			<!-- start-smoth-scrolling -->
			<script type="text/javascript" src="{% static 'js/move-top.js' %}"></script>
			<script type="text/javascript" src="{% static 'js/easing.js' %}"></script>
			<script type="text/javascript">
				jQuery(document).ready(function($) {
					$(".scroll").click(function(event){		
						event.preventDefault();
						$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
					});
				});
			</script>
			<!-- start-smoth-scrolling -->
		<!-- //here ends scrolling icon -->
</html>
